name: 'dbt_crypto'
version: '1.0.0'
config-version: 2

profile: 'dbt_crypto'

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_crypto:
    staging:
      +materialized: view
    marts:
      +materialized: table
